// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWME_6bpS2YR2leM9QMwcBHwuISViNil4',
    appId: '1:724580316142:web:166925c9853043bb8f14ff',
    messagingSenderId: '724580316142',
    projectId: 'prompt-mixer-b4fb5',
    authDomain: 'prompt-mixer-b4fb5.firebaseapp.com',
    storageBucket: 'prompt-mixer-b4fb5.firebasestorage.app',
    measurementId: 'G-BX5QBL9YDZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWME_6bpS2YR2leM9QMwcBHwuISViNil4',
    appId: '1:724580316142:android:166925c9853043bb8f14ff',
    messagingSenderId: '724580316142',
    projectId: 'prompt-mixer-b4fb5',
    authDomain: 'prompt-mixer-b4fb5.firebaseapp.com',
    storageBucket: 'prompt-mixer-b4fb5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWME_6bpS2YR2leM9QMwcBHwuISViNil4',
    appId: '1:724580316142:ios:166925c9853043bb8f14ff',
    messagingSenderId: '724580316142',
    projectId: 'prompt-mixer-b4fb5',
    authDomain: 'prompt-mixer-b4fb5.firebaseapp.com',
    storageBucket: 'prompt-mixer-b4fb5.firebasestorage.app',
    iosBundleId: 'com.promptmixer.prompts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWME_6bpS2YR2leM9QMwcBHwuISViNil4',
    appId: '1:724580316142:ios:166925c9853043bb8f14ff',
    messagingSenderId: '724580316142',
    projectId: 'prompt-mixer-b4fb5',
    authDomain: 'prompt-mixer-b4fb5.firebaseapp.com',
    storageBucket: 'prompt-mixer-b4fb5.firebasestorage.app',
    iosBundleId: 'com.promptmixer.prompts',
  );
}
